
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEARRAY COLON COMMA DEF DIVIDE EQUALS ID LBRACE LBRACKET LPAREN MINUS NUMBER OBJECT PLUS PRINTLN RBRACE RBRACKET RPAREN SEMI STRING STRING_LITERAL TIMES UNITprogram : OBJECT ID LBRACE main_def RBRACEmain_def : DEF ID LPAREN args RPAREN COLON UNIT EQUALS LBRACE stmt_list RBRACEargs : ID COLON ARRAY LBRACKET STRING RBRACKETstmt_list : stmt_list stmt\n                 | stmtstmt : PRINTLN LPAREN STRING_LITERAL RPAREN SEMI'
    
_lr_action_items = {'OBJECT':([0,],[2,]),'$end':([1,7,],[0,-1,]),'ID':([2,6,9,],[3,8,10,]),'LBRACE':([3,19,],[4,21,]),'DEF':([4,],[6,]),'RBRACE':([5,22,23,25,26,30,],[7,25,-5,-2,-4,-6,]),'LPAREN':([8,24,],[9,27,]),'COLON':([10,13,],[12,15,]),'RPAREN':([11,20,28,],[13,-3,29,]),'ARRAY':([12,],[14,]),'LBRACKET':([14,],[16,]),'UNIT':([15,],[17,]),'STRING':([16,],[18,]),'EQUALS':([17,],[19,]),'RBRACKET':([18,],[20,]),'PRINTLN':([21,22,23,26,30,],[24,24,-5,-4,-6,]),'STRING_LITERAL':([27,],[28,]),'SEMI':([29,],[30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'main_def':([4,],[5,]),'args':([9,],[11,]),'stmt_list':([21,],[22,]),'stmt':([21,22,],[23,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> OBJECT ID LBRACE main_def RBRACE','program',5,'p_program','analizador.py',75),
  ('main_def -> DEF ID LPAREN args RPAREN COLON UNIT EQUALS LBRACE stmt_list RBRACE','main_def',11,'p_main_def','analizador.py',79),
  ('args -> ID COLON ARRAY LBRACKET STRING RBRACKET','args',6,'p_args','analizador.py',83),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','analizador.py',87),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','analizador.py',88),
  ('stmt -> PRINTLN LPAREN STRING_LITERAL RPAREN SEMI','stmt',5,'p_stmt','analizador.py',92),
]
